# Generated by Django 3.2 on 2021-04-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_characters_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universe',
            name='image_Universe',
        ),
    ]
