# Generated by Django 3.2 on 2021-04-18 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('imagen', models.CharField(max_length=220)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Powers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'powers',
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_foundation', models.DateField()),
                ('image_universe' , models.CharField(max_length=220))
            ],
            options={
                'db_table': 'universe',
            },
        ),
        migrations.CreateModel(
            name='powers_character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.characters')),
                ('powers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.powers')),
            ],
            options={
                'db_table': 'powers_characters',
            },
        ),
        migrations.AddField(
            model_name='characters',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.universe'),
        ),
    ]
