# Generated by Django 3.2 on 2021-04-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='description',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
