# Generated by Django 3.2 on 2021-04-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_universe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universe',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
